export type SeriesPoint = { date: string; value: number };
export type Breakdown = {
  label: string;
  orders: number;
  revenue: number;
  customers?: number;
};
export type ErpDashboardResponse = {
  kpis: {
    grossRevenue: number;
    netRevenue: number;
    discountAmount: number;
    orders: number;
    totalQuantity: number;
    returnedQuantity: number;
    uniqueCustomers: number;
    newCustomers: number | null;
    returningCustomers: number;
    retentionPct: number;
    cancelledOrders: number;
    cancelledAmount: number;
    avgTicket: number;
    returnAmount: number;
    avgItemsPerOrder: number;
    returnRatePct: number;
    discountRatePct: number;
  };
  revenueOverTime: SeriesPoint[];
  ordersOverTime: SeriesPoint[];
  newCustomersOverTime: SeriesPoint[];
  returningCustomersOverTime: SeriesPoint[];
  attribution: {
    attributedCustomers: number;
    unattributedCustomers: number;
    attributedRevenue: number;
    unattributedRevenue: number;
  };
  breakdowns: {
    statuses: Breakdown[];
    payments: Breakdown[];
    sellers: Breakdown[];
    stores: Breakdown[];
    states: Breakdown[];
  };
};
export type ErpOrderItem = {
  id: string;
  sku: string | null;
  productId: string | null;
  name: string | null;
  category: string | null;
  color: string | null;
  size: string | null;
  quantity: number;
  unitPrice: number;
  costPrice: number;
  discountAmount: number;
  grossAmount: number;
  netAmount: number;
};
export type ErpOrderRow = {
  id: string;
  createdAt: string;
  customerId: string | null;
  customerName: string | null;
  company: string | null;
  document: string | null;
  seller: string | null;
  store: string | null;
  paymentMethod: string | null;
  freightAmount: number;
  channel: string;
  status: string | null;
  requestedQuantity: number;
  fulfilledQuantity: number;
  returnedQuantity: number;
  grossAmount: number;
  discountAmount: number;
  netAmount: number;
  returnAmount: number;
  state: string | null;
  city: string | null;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  attributed: boolean;
  items: ErpOrderItem[];
};
export type ErpOrdersResponse = { rows: ErpOrderRow[]; total: number };
export type ErpCustomerRow = {
  id: string;
  name: string | null;
  company: string | null;
  document: string | null;
  email: string | null;
  phone: string | null;
  city: string | null;
  state: string | null;
  seller: string | null;
  orders: number;
  totalSpent: number;
  averageTicket: number;
  historicalOrders: number;
  lifetimeValue: number | null;
  observedLifetimeValue: number;
  buyerType: "NEW" | "RETURNING";
  daysSinceLastOrder: number | null;
  segment: "CHAMPION" | "LOYAL" | "POTENTIAL" | "AT_RISK";
  firstOrderAt: string | null;
  lastOrderAt: string | null;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  attributed: boolean;
};
export type ErpCustomersResponse = { rows: ErpCustomerRow[]; total: number };
export type ErpProductVariant = {
  id: string;
  sku: string;
  color: string | null;
  size: string | null;
  units: number;
  revenue: number;
  averagePrice: number;
  catalogPrice: number;
  stock: number;
  turnoverPct: number;
  salesPower: number;
  costAmount: number;
  grossProfit: number;
  grossMarginPct: number;
  coverageDays: number | null;
};
export type ErpProductRow = {
  id: string;
  name: string | null;
  category: string | null;
  units: number;
  revenue: number;
  averagePrice: number;
  stock: number;
  turnoverPct: number;
  salesPower: number;
  costAmount: number;
  grossProfit: number;
  grossMarginPct: number;
  coverageDays: number | null;
  variantCount: number;
  outOfStockCount: number;
  variants: ErpProductVariant[];
};
export type ProductBreakdown = {
  label: string;
  units: number;
  revenue: number;
  stock?: number;
  salesPower?: number;
};
export type ErpProductsResponse = {
  rows: ErpProductRow[];
  total: number;
  totalSkus: number;
  filteredTotal: number;
  totalRevenue: number;
  totalUnits: number;
  totalStock: number;
  outOfStockCount: number;
  turnoverPct: number;
  salesPower: number;
  totalCost: number;
  grossProfit: number;
  grossMarginPct: number;
  negativeStockCount: number;
  coverageDays: number | null;
  breakdowns: {
    categories: ProductBreakdown[];
    colors: ProductBreakdown[];
    sizes: ProductBreakdown[];
  };
};

export interface ErpData {
  dashboard: ErpDashboardResponse;
  orders: ErpOrderRow[];
  history: ErpOrderRow[];
  customers: ErpCustomerRow[];
  products: ErpProductsResponse;
}
