-- PROPOSTA; NÃO EXECUTADA. Não incluída no Terraform ativo.
CREATE TABLE IF NOT EXISTS `${project_id}.up_analytics.analytics_customer_metrics` (
  `row_key` STRING NOT NULL,
  `store_id` STRING NOT NULL,
  `currency` STRING,
  `reporting_timezone` STRING,
  `policy_hash` STRING,
  `analytics_version` STRING,
  `calculated_at` TIMESTAMP,
  `history_complete` BOOL,
  `customer_id` STRING,
  `customer_type` STRING,
  `ltv_basis` STRING,
  `first_purchase_date` DATE,
  `purchases` INT64,
  `first_purchase_at` TIMESTAMP,
  `second_purchase_at` TIMESTAMP,
  `third_purchase_at` TIMESTAMP,
  `fourth_purchase_at` TIMESTAMP,
  `observed_through` TIMESTAMP,
  `ltv_lifetime_observed` NUMERIC,
  `ltv_paid` NUMERIC,
  `days_first_to_second` NUMERIC,
  `days_second_to_third` NUMERIC,
  `days_third_to_fourth` NUMERIC,
  `ltv_30d` NUMERIC,
  `ltv_60d` NUMERIC,
  `ltv_90d` NUMERIC,
  `ltv_180d` NUMERIC,
  `ltv_365d` NUMERIC,
  `ltv_30d_complete` BOOL,
  `ltv_60d_complete` BOOL,
  `ltv_90d_complete` BOOL,
  `ltv_180d_complete` BOOL,
  `ltv_365d_complete` BOOL
)
CLUSTER BY store_id, customer_id, policy_hash;
