-- PROPOSTA; NÃO EXECUTADA. Não incluída no Terraform ativo.
CREATE TABLE IF NOT EXISTS `${project_id}.up_analytics.analytics_store_daily` (
  `row_key` STRING NOT NULL,
  `store_id` STRING NOT NULL,
  `currency` STRING,
  `reporting_timezone` STRING,
  `policy_hash` STRING,
  `analytics_version` STRING,
  `calculated_at` TIMESTAMP,
  `history_complete` BOOL,
  `order_date` DATE,
  `payment_date` DATE,
  `orders_generated` INT64,
  `orders_paid` INT64,
  `orders_cancelled` INT64,
  `approved_orders` INT64,
  `new_customers` INT64,
  `returning_customers` INT64,
  `purchasing_customers` INT64,
  `orders_without_customer` INT64,
  `meta_impressions` INT64,
  `meta_clicks` INT64,
  `first_party_new_customers_attributed` INT64,
  `first_party_orders_attributed` INT64,
  `revenue_generated` NUMERIC,
  `revenue_fulfilled` NUMERIC,
  `revenue_paid` NUMERIC,
  `revenue_cancelled` NUMERIC,
  `revenue_unfulfilled` NUMERIC,
  `approval_rate` NUMERIC,
  `average_order_value_generated` NUMERIC,
  `average_order_value_paid` NUMERIC,
  `items_per_order_generated` NUMERIC,
  `items_per_order_fulfilled` NUMERIC,
  `meta_spend` NUMERIC,
  `meta_reported_purchases` NUMERIC,
  `meta_reported_purchase_value` NUMERIC,
  `first_party_revenue_generated_attributed` NUMERIC,
  `first_party_revenue_paid_attributed` NUMERIC,
  `new_customer_cac` NUMERIC,
  `roas_generated` NUMERIC,
  `roas_paid` NUMERIC,
  `observation_complete` BOOL
)
PARTITION BY order_date
CLUSTER BY store_id, policy_hash;
