import type { Metric, Operation } from "@/types/domain";
import type { ReadResource } from "@/services/api/http";
export type TemplateId =
  "current-standard.v1" | "b2b-standard.v2" | "b2c-standard.v2";
export type WidgetSize = "full" | "half";
export type ManagerPage = {
  path: string;
  title: string;
  group: string;
  metricIds: string[];
  body: string | null;
  resource: ReadResource;
  widgets: string[];
};
export type RegisteredMetric = {
  id: string;
  label: string;
  format: Metric["format"];
};
export const MetricRegistry: Readonly<Record<string, RegisteredMetric>> = {
  erp_revenue_paid: {
    id: "erp_revenue_paid",
    label: "Faturamento pago ERP",
    format: "currency",
  },
  erp_orders_paid: {
    id: "erp_orders_paid",
    label: "Pedidos pagos ERP",
    format: "number",
  },
  ecommerce_revenue_paid: {
    id: "ecommerce_revenue_paid",
    label: "Faturamento pago Ecommerce",
    format: "currency",
  },
  ad_revenue_paid: {
    id: "ad_revenue_paid",
    label: "Faturamento pago via anúncios",
    format: "currency",
  },
  roas_paid: {
    id: "roas_paid",
    label: "ROAS pago",
    format: "ratio",
  },
  total_media_spend: {
    id: "total_media_spend",
    label: "Investimento total em Ads",
    format: "currency",
  },
  erp_ad_share: {
    id: "erp_ad_share",
    label: "% faturamento ERP atribuído aos anúncios",
    format: "percent",
  },
  new_customers: {
    id: "new_customers",
    label: "Novos clientes adquiridos",
    format: "number",
  },
  new_revenue_paid: {
    id: "new_revenue_paid",
    label: "Faturamento novos clientes",
    format: "currency",
  },
  new_sales_paid: {
    id: "new_sales_paid",
    label: "Vendas novos clientes",
    format: "number",
  },
  new_ad_customers: {
    id: "new_ad_customers",
    label: "Novos clientes vindos de anúncios",
    format: "number",
  },
  repurchasers: {
    id: "repurchasers",
    label: "Clientes que recompraram",
    format: "number",
  },
  repurchase_revenue_paid: {
    id: "repurchase_revenue_paid",
    label: "Faturamento recompra",
    format: "currency",
  },
  repurchase_sales_paid: {
    id: "repurchase_sales_paid",
    label: "Vendas recompra",
    format: "number",
  },
  revenue_paid: {
    id: "revenue_paid",
    label: "Faturamento",
    format: "currency",
  },
  meta_spend: {
    id: "meta_spend",
    label: "Investimento Meta",
    format: "currency",
  },
  google_spend: {
    id: "google_spend",
    label: "Investimento Google",
    format: "currency",
  },
  new_ticket_paid: {
    id: "new_ticket_paid",
    label: "Ticket Aquisição",
    format: "currency",
  },
  repurchase_ticket_paid: {
    id: "repurchase_ticket_paid",
    label: "Ticket Retenção",
    format: "currency",
  },
  approved_conversion: {
    id: "approved_conversion",
    label: "Conversão Aprovados",
    format: "percent",
  },
  cac: {
    id: "cac",
    label: "CAC",
    format: "currency",
  },
  approved_registrations: {
    id: "approved_registrations",
    label: "Cadastros Aprovados",
    format: "number",
  },
  registrations: {
    id: "registrations",
    label: "Cadastros Gerados",
    format: "number",
  },
  approved_registration_cost: {
    id: "approved_registration_cost",
    label: "Custo por Cadastro Aprovado",
    format: "currency",
  },
  approval_rate: {
    id: "approval_rate",
    label: "Taxa de Aprovação",
    format: "percent",
  },
  roas_requested: {
    id: "roas_requested",
    label: "ROAS Solicitado",
    format: "ratio",
  },
  registration_cost: {
    id: "registration_cost",
    label: "Custo por cadastro",
    format: "currency",
  },
  approved_converted: {
    id: "approved_converted",
    label: "Aprovados convertidos",
    format: "number",
  },
  registration_first_purchase_mean: {
    id: "registration_first_purchase_mean",
    label: "Tempo médio cadastro → primeira compra",
    format: "days",
  },
  registration_first_purchase_median: {
    id: "registration_first_purchase_median",
    label: "Mediana cadastro → primeira compra",
    format: "days",
  },
  recurring_customers: {
    id: "recurring_customers",
    label: "Clientes recorrentes",
    format: "number",
  },
  recurring_revenue_paid: {
    id: "recurring_revenue_paid",
    label: "Faturamento recorrente",
    format: "currency",
  },
  recurring_ticket_paid: {
    id: "recurring_ticket_paid",
    label: "Ticket recorrente",
    format: "currency",
  },
  recurring_sales_paid: {
    id: "recurring_sales_paid",
    label: "Vendas recorrentes",
    format: "number",
  },
  reactivated_customers: {
    id: "reactivated_customers",
    label: "Clientes reativados",
    format: "number",
  },
  reactivated_revenue_paid: {
    id: "reactivated_revenue_paid",
    label: "Faturamento reativado",
    format: "currency",
  },
  reactivated_ticket_paid: {
    id: "reactivated_ticket_paid",
    label: "Ticket reativado",
    format: "currency",
  },
  reactivated_sales_paid: {
    id: "reactivated_sales_paid",
    label: "Vendas reativadas",
    format: "number",
  },
  repeat_mean_days: {
    id: "repeat_mean_days",
    label: "Tempo médio entre compras",
    format: "days",
  },
  repeat_median_days: {
    id: "repeat_median_days",
    label: "Mediana entre compras",
    format: "days",
  },
  orders_generated: {
    id: "orders_generated",
    label: "Vendas",
    format: "number",
  },
  roas_approved: {
    id: "roas_approved",
    label: "ROAS Geral",
    format: "ratio",
  },
  cost_per_sale: {
    id: "cost_per_sale",
    label: "CPA Geral",
    format: "currency",
  },
  repurchase_rate: {
    id: "repurchase_rate",
    label: "Taxa de Recompra",
    format: "percent",
  },
  ltv_complete: {
    id: "ltv_complete",
    label: "LTV da Base",
    format: "currency",
  },
  revenue_captured: {
    id: "revenue_captured",
    label: "Faturamento",
    format: "currency",
  },
  roas_captured: {
    id: "roas_captured",
    label: "ROAS",
    format: "ratio",
  },
  cpm: {
    id: "cpm",
    label: "CPM",
    format: "currency",
  },
  ctr: {
    id: "ctr",
    label: "CTR",
    format: "percent",
  },
  cpc: {
    id: "cpc",
    label: "CPC",
    format: "currency",
  },
  revenue_approved: {
    id: "revenue_approved",
    label: "revenue_approved",
    format: "currency",
  },
  revenue_cancelled: {
    id: "revenue_cancelled",
    label: "revenue_cancelled",
    format: "currency",
  },
  average_ticket: {
    id: "average_ticket",
    label: "average_ticket",
    format: "currency",
  },
  orders_paid: {
    id: "orders_paid",
    label: "orders_paid",
    format: "number",
  },
  tiktok_spend: {
    id: "tiktok_spend",
    label: "tiktok_spend",
    format: "currency",
  },
  sessions: {
    id: "sessions",
    label: "sessions",
    format: "number",
  },
  cost_per_session: {
    id: "cost_per_session",
    label: "cost_per_session",
    format: "currency",
  },
  final_conversion_rate: {
    id: "final_conversion_rate",
    label: "final_conversion_rate",
    format: "percent",
  },
  add_to_cart: {
    id: "add_to_cart",
    label: "add_to_cart",
    format: "number",
  },
  cost_per_add_to_cart: {
    id: "cost_per_add_to_cart",
    label: "cost_per_add_to_cart",
    format: "currency",
  },
  session_to_cart_rate: {
    id: "session_to_cart_rate",
    label: "session_to_cart_rate",
    format: "percent",
  },
  checkout_started: {
    id: "checkout_started",
    label: "checkout_started",
    format: "number",
  },
  cost_per_checkout: {
    id: "cost_per_checkout",
    label: "cost_per_checkout",
    format: "currency",
  },
  cart_to_checkout_rate: {
    id: "cart_to_checkout_rate",
    label: "cart_to_checkout_rate",
    format: "percent",
  },
  checkout_to_sale_rate: {
    id: "checkout_to_sale_rate",
    label: "checkout_to_sale_rate",
    format: "percent",
  },
};
export const WidgetRegistry: Readonly<
  Record<string, { label: string; sizes: readonly WidgetSize[] }>
> = {
  "commercial-trend": {
    label: "Solicitado × Atendido — evidência comercial observada",
    sizes: ["full", "half"],
  },
  "paid-media-trend": {
    label: "Faturamento Pago × Investimento",
    sizes: ["full", "half"],
  },
  "acquisition-retention": {
    label: "Aquisição × Retenção",
    sizes: ["full", "half"],
  },
  funnel: {
    label: "Funil de Conversão",
    sizes: ["full", "half"],
  },
  "new-revenue-ticket": {
    label: "Faturamento × Ticket",
    sizes: ["full", "half"],
  },
  "new-sales-customers": {
    label: "Vendas × Clientes",
    sizes: ["full", "half"],
  },
  "investment-cac": {
    label: "Investimento × CAC",
    sizes: ["full", "half"],
  },
  "approved-conversion": {
    label: "Aprovados × Conversão",
    sizes: ["full", "half"],
  },
  "registration-cohort": {
    label: "Cohort de cadastro",
    sizes: ["full", "half"],
  },
  "repeat-revenue-ticket": {
    label: "Faturamento × Ticket",
    sizes: ["full", "half"],
  },
  "recurring-reactivated": {
    label: "Recorrentes × Reativados",
    sizes: ["full", "half"],
  },
  "repurchase-cohort": {
    label: "Cohort de recompra",
    sizes: ["full", "half"],
  },
  "purchase-progression": {
    label: "Progressão de compras observadas",
    sizes: ["full", "half"],
  },
  "journey-guidance": {
    label: "Jornada & Atribuição",
    sizes: ["full", "half"],
  },
  "monthly-history": {
    label: "Histórico Mensal",
    sizes: ["full", "half"],
  },
  "provider-unavailable": {
    label: "Fonte ainda não disponível",
    sizes: ["full", "half"],
  },
  "retail-overview": {
    label: "Resumo de vendas",
    sizes: ["full", "half"],
  },
  "retail-retention": {
    label: "Retenção por período, progressão e cohort",
    sizes: ["full", "half"],
  },
  "retail-platforms": {
    label: "Mídia por plataforma",
    sizes: ["full", "half"],
  },
  "retail-funnel": {
    label: "Funil do Ecommerce",
    sizes: ["full", "half"],
  },
  forecast: {
    label: "Forecast / Planejamento",
    sizes: ["full", "half"],
  },
};
export const managerPages: readonly ManagerPage[] = [
  {
    path: "/b2b",
    title: "Visão Geral",
    group: "Visão Geral",
    metricIds: [
      "erp_revenue_paid",
      "erp_orders_paid",
      "ecommerce_revenue_paid",
      "ad_revenue_paid",
      "roas_paid",
      "total_media_spend",
      "erp_ad_share",
      "new_customers",
      "new_revenue_paid",
      "new_sales_paid",
      "new_ad_customers",
      "repurchasers",
      "repurchase_revenue_paid",
      "repurchase_sales_paid",
    ],
    body: null,
    resource: "overview",
    widgets: ["commercial-trend"],
  },
  {
    path: "/b2b/performance",
    title: "Visão Geral",
    group: "Performance",
    metricIds: [
      "revenue_paid",
      "roas_paid",
      "total_media_spend",
      "meta_spend",
      "google_spend",
      "new_revenue_paid",
      "new_ticket_paid",
      "new_sales_paid",
      "repurchase_revenue_paid",
      "repurchase_ticket_paid",
      "repurchase_sales_paid",
      "approved_conversion",
      "cac",
      "approved_registrations",
      "registrations",
      "approved_registration_cost",
      "approval_rate",
    ],
    body: null,
    resource: "performance",
    widgets: ["paid-media-trend", "acquisition-retention"],
  },
  {
    path: "/b2b/performance/funnel",
    title: "Funil de Conversão",
    group: "Performance",
    metricIds: [
      "total_media_spend",
      "roas_requested",
      "roas_paid",
      "approved_conversion",
    ],
    body: null,
    resource: "funnel",
    widgets: ["funnel"],
  },
  {
    path: "/b2b/performance/new-customers",
    title: "Novos Clientes",
    group: "Performance",
    metricIds: [
      "new_revenue_paid",
      "new_ticket_paid",
      "new_sales_paid",
      "new_customers",
      "cac",
      "registration_cost",
      "approved_registration_cost",
      "total_media_spend",
      "approved_registrations",
      "approved_converted",
      "approved_conversion",
      "registration_first_purchase_mean",
      "registration_first_purchase_median",
    ],
    body: null,
    resource: "acquisition",
    widgets: [
      "new-revenue-ticket",
      "new-sales-customers",
      "investment-cac",
      "approved-conversion",
      "registration-cohort",
    ],
  },
  {
    path: "/b2b/performance/repurchase",
    title: "Recompra",
    group: "Performance",
    metricIds: [
      "repurchase_revenue_paid",
      "repurchase_ticket_paid",
      "repurchase_sales_paid",
      "repurchasers",
      "recurring_customers",
      "recurring_revenue_paid",
      "recurring_ticket_paid",
      "recurring_sales_paid",
      "reactivated_customers",
      "reactivated_revenue_paid",
      "reactivated_ticket_paid",
      "reactivated_sales_paid",
      "repeat_mean_days",
      "repeat_median_days",
    ],
    body: null,
    resource: "retention",
    widgets: [
      "repeat-revenue-ticket",
      "recurring-reactivated",
      "repurchase-cohort",
      "purchase-progression",
    ],
  },
  {
    path: "/b2b/performance/registrations",
    title: "Cadastros",
    group: "Performance",
    metricIds: [
      "approved_registrations",
      "approved_converted",
      "approved_conversion",
    ],
    body: null,
    resource: "acquisition",
    widgets: [],
  },
  {
    path: "/b2b/performance/ads",
    title: "Anúncios",
    group: "Performance",
    metricIds: [],
    body: "campaigns",
    resource: "performance",
    widgets: [],
  },
  {
    path: "/b2b/performance/journey",
    title: "Jornada & Atribuição",
    group: "Performance",
    metricIds: [],
    body: null,
    resource: "performance",
    widgets: ["journey-guidance"],
  },
  {
    path: "/b2b/ecommerce/overview",
    title: "Visão Geral",
    group: "Ecommerce",
    metricIds: [],
    body: "overview",
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2b/ecommerce/orders",
    title: "Pedidos",
    group: "Ecommerce",
    metricIds: [],
    body: "orders",
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2b/ecommerce/registrations",
    title: "Cadastros",
    group: "Ecommerce",
    metricIds: [
      "approved_registrations",
      "approved_converted",
      "approved_conversion",
    ],
    body: null,
    resource: "acquisition",
    widgets: [],
  },
  {
    path: "/b2b/ecommerce/products",
    title: "Produtos",
    group: "Ecommerce",
    metricIds: [],
    body: "products",
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2b/ecommerce/stock",
    title: "Estoque",
    group: "Ecommerce",
    metricIds: [],
    body: "stock",
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2b/ecommerce/sellers",
    title: "Vendedores",
    group: "Ecommerce",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2b/ecommerce/geography",
    title: "Geografia",
    group: "Ecommerce",
    metricIds: [],
    body: "geography",
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2b/ecommerce/customers",
    title: "Inteligência de Clientes",
    group: "Ecommerce",
    metricIds: [],
    body: "customers",
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2b/ecommerce/history",
    title: "Histórico Mensal",
    group: "Ecommerce",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["monthly-history"],
  },
  {
    path: "/b2b/erp/overview",
    title: "Visão Geral",
    group: "ERP",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["provider-unavailable"],
  },
  {
    path: "/b2b/erp/orders",
    title: "Pedidos",
    group: "ERP",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["provider-unavailable"],
  },
  {
    path: "/b2b/erp/customers",
    title: "Clientes",
    group: "ERP",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["provider-unavailable"],
  },
  {
    path: "/b2b/erp/products",
    title: "Produtos",
    group: "ERP",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["provider-unavailable"],
  },
  {
    path: "/b2b/erp/stock",
    title: "Estoque",
    group: "ERP",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["provider-unavailable"],
  },
  {
    path: "/b2b/erp/sellers",
    title: "Vendedoras e Lojas",
    group: "ERP",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["provider-unavailable"],
  },
  {
    path: "/b2b/erp/geography",
    title: "Geografia",
    group: "ERP",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["provider-unavailable"],
  },
  {
    path: "/b2b/whatsapp/analysis",
    title: "Análise de Atendimento",
    group: "WhatsApp",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["provider-unavailable"],
  },
  {
    path: "/b2b/whatsapp/conversations",
    title: "Conversas",
    group: "WhatsApp",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["provider-unavailable"],
  },
  {
    path: "/b2b/whatsapp/connections",
    title: "Conexões",
    group: "WhatsApp",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["provider-unavailable"],
  },
  {
    path: "/b2c",
    title: "Visão Geral",
    group: "Visão Geral",
    metricIds: [
      "orders_generated",
      "total_media_spend",
      "roas_approved",
      "cost_per_sale",
    ],
    body: null,
    resource: "overview",
    widgets: ["retail-overview"],
  },
  {
    path: "/b2c/orders",
    title: "Pedidos",
    group: "Pedidos",
    metricIds: [],
    body: "retail-orders",
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2c/customers/overview",
    title: "Visão Geral",
    group: "Clientes",
    metricIds: [
      "new_customers",
      "recurring_customers",
      "repurchase_rate",
      "ltv_complete",
    ],
    body: null,
    resource: "overview",
    widgets: ["retail-retention"],
  },
  {
    path: "/b2c/customers",
    title: "Lista de Clientes",
    group: "Clientes",
    metricIds: [],
    body: "customers",
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2c/products",
    title: "Análise de Produtos",
    group: "Produtos",
    metricIds: [],
    body: "retail-products",
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2c/stock",
    title: "Estoque",
    group: "Produtos",
    metricIds: [],
    body: "retail-stock",
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2c/performance",
    title: "Mídia e Conversão Geral",
    group: "Performance",
    metricIds: [
      "total_media_spend",
      "orders_generated",
      "revenue_captured",
      "roas_captured",
      "cpm",
      "ctr",
      "cpc",
    ],
    body: null,
    resource: "overview",
    widgets: ["retail-platforms"],
  },
  {
    path: "/b2c/performance/funnel",
    title: "Funil do Ecommerce",
    group: "Performance",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["retail-funnel"],
  },
  {
    path: "/b2c/performance/campaigns",
    title: "Campanhas",
    group: "Performance",
    metricIds: [],
    body: "campaigns",
    resource: "overview",
    widgets: [],
  },
  {
    path: "/b2c/performance/history",
    title: "Histórico de Performance",
    group: "Performance",
    metricIds: [],
    body: null,
    resource: "overview",
    widgets: ["monthly-history"],
  },
];
export const DashboardTemplateRegistry = {
  "current-standard.v1": { label: "Padrão atual · V1", operation: null },
  "b2b-standard.v2": { label: "Gestão B2B · V2", operation: "B2B" },
  "b2c-standard.v2": { label: "Gestão B2C · V2", operation: "B2C" },
} as const;
export const AvailabilityRegistry = {
  certified: {
    label: "Dados reais",
    reason: "Evidência certificada na publicação atual.",
  },
  observed: {
    label: "Observado",
    reason: "Histórico observado; não comprova lifetime ou pagamento.",
  },
  unavailable: {
    label: "Indisponível",
    reason: "Fonte ainda não disponível / cobertura ainda não certificada.",
  },
} as const;
export const FilterRegistry = {
  type: {
    label: "Tipo",
    values: [
      "Todos os anúncios",
      "Anúncios · ERP direto",
      "Anúncios · Ecommerce",
      "Ecommerce",
      "ERP",
    ],
    supported: false,
  },
  status: {
    label: "Status",
    values: ["Pago", "Solicitado", "Cancelado", "Espera"],
    supported: false,
  },
  origin: { label: "Origem", values: ["Todas"], supported: false },
  state: { label: "Estado", values: ["Todos"], supported: false },
  seller: { label: "Vendedora", values: ["Todas"], supported: false },
  comparison: {
    label: "Comparar período",
    values: ["Período anterior", "Sem comparação"],
    supported: true,
  },
} as const;
const aliases: Record<string, string> = {
  "/b2b/commercial": "/b2b/ecommerce/orders",
  "/b2b/acquisition": "/b2b/performance/new-customers",
  "/b2b/retention": "/b2b/performance/repurchase",
  "/b2b/repurchase": "/b2b/performance/repurchase",
  "/b2b/customers": "/b2b/ecommerce/customers",
  "/b2b/products": "/b2b/ecommerce/products",
  "/b2b/geography": "/b2b/ecommerce/geography",
  "/b2b/funnel": "/b2b/performance/funnel",
  "/b2c/revenue": "/b2c/orders",
  "/b2c/media": "/b2c/performance",
  "/b2c/funnel": "/b2c/performance/funnel",
  "/b2c/retention": "/b2c/customers/overview",
  "/b2c/grade": "/b2c/stock",
};
export function managerPage(path: string) {
  return managerPages.find((p) => p.path === (aliases[path] ?? path));
}
export function templateFor(operation: Operation): TemplateId {
  return operation === "B2B" ? "b2b-standard.v2" : "b2c-standard.v2";
}
export function pageWidgetIds(page: ManagerPage) {
  return [
    ...(page.metricIds.length ? ["metrics"] : []),
    ...(page.body ? ["content"] : []),
    ...page.widgets,
  ];
}
