import {
  LayoutDashboard,
  ReceiptText,
  UserPlus,
  Repeat2,
  Package,
  MapPin,
  TrendingUp,
  Users,
  ChartNoAxesCombined,
  Settings,
  Database,
} from "lucide-react";
export const navigation = [
  { label: "Overview", href: "/b2b", icon: LayoutDashboard, operation: "B2B" },
  {
    label: "Pedidos",
    href: "/b2b/commercial",
    icon: ReceiptText,
    operation: "B2B",
  },
  {
    label: "Aquisição",
    href: "/b2b/acquisition",
    icon: UserPlus,
    operation: "B2B",
  },
  {
    label: "Retenção",
    href: "/b2b/retention",
    icon: Repeat2,
    operation: "B2B",
  },
  { label: "Clientes", href: "/b2b/customers", icon: Users, operation: "B2B" },
  { label: "Produtos", href: "/b2b/products", icon: Package, operation: "B2B" },
  {
    label: "Geografia",
    href: "/b2b/geography",
    icon: MapPin,
    operation: "B2B",
  },
  {
    label: "Performance",
    href: "/b2b/performance",
    icon: TrendingUp,
    operation: "B2B",
  },
  { label: "Overview", href: "/b2c", icon: LayoutDashboard, operation: "B2C" },
  {
    label: "Pedidos",
    href: "/b2c/orders",
    icon: ReceiptText,
    operation: "B2C",
  },
  { label: "Clientes", href: "/b2c/customers", icon: Users, operation: "B2C" },
  {
    label: "Retenção",
    href: "/b2c/retention",
    icon: Repeat2,
    operation: "B2C",
  },
  {
    label: "Análise de Produtos",
    href: "/b2c/products",
    icon: Package,
    operation: "B2C",
  },
  { label: "Estoque", href: "/b2c/stock", icon: Database, operation: "B2C" },
  {
    label: "Performance",
    href: "/b2c/performance",
    icon: ChartNoAxesCombined,
    operation: "B2C",
  },
  {
    label: "ERP",
    href: "/erp",
    icon: Database,
    children: [
      ["Overview", "/erp"],
      ["Pedidos", "/erp/pedidos"],
      ["Clientes", "/erp/clientes"],
      ["Produtos", "/erp/produtos"],
      ["Estoque", "/erp/estoque"],
      ["Vendedores", "/erp/vendedores"],
    ],
  },
  {
    label: "Campanhas",
    href: "/campaigns/meta",
    icon: ChartNoAxesCombined,
    children: [
      ["Meta Ads", "/campaigns/meta"],
      ["Google Ads", "/campaigns/google"],
      ["Pinterest Ads", "/campaigns/pinterest"],
      ["TikTok Ads", "/campaigns/tiktok"],
    ],
  },
  { label: "Configurações", href: "/settings", icon: Settings },
];
