CREATE TABLE IF NOT EXISTS `${project_id}.up_ops.installation_work_units` (
  `row_key` STRING NOT NULL,
  `work_unit_id` STRING NOT NULL,
  `plan_id` STRING NOT NULL,
  `store_id` STRING NOT NULL,
  `source` STRING NOT NULL,
  `connection_id` STRING NOT NULL,
  `pipeline` STRING NOT NULL,
  `resource` STRING NOT NULL,
  `unit_kind` STRING NOT NULL,
  `mode` STRING NOT NULL,
  `status` STRING NOT NULL,
  `dispatch_token` STRING,
  `dispatch_operation_name` STRING,
  `execution_name` STRING,
  `checkpoint_plan_key` STRING,
  `run_id` STRING,
  `last_error_code` STRING,
  `sequence` INT64 NOT NULL,
  `revision` INT64 NOT NULL,
  `reservation_revision` INT64,
  `attempt_count` INT64 NOT NULL,
  `failure_count` INT64 NOT NULL,
  `records_processed` INT64,
  `pages_processed` INT64,
  `next_eligible_at` TIMESTAMP,
  `started_at` TIMESTAMP,
  `updated_at` TIMESTAMP,
  `finished_at` TIMESTAMP,
  `filters` JSON NOT NULL,
  `dependencies` JSON NOT NULL,
  `required` BOOL NOT NULL,
  `duration_seconds` FLOAT64,
  `slice_seconds` FLOAT64
)
CLUSTER BY store_id, status, plan_id, resource;
