CREATE TABLE IF NOT EXISTS `${project_id}.up_ops.store_runtime_config` (
  `row_key` STRING NOT NULL,
  `store_id` STRING NOT NULL,
  `status` STRING NOT NULL,
  `revision` INT64 NOT NULL,
  `store_name` STRING,
  `store_slug` STRING,
  `timezone` STRING,
  `currency` STRING,
  `policy_version` STRING,
  `upzero_connection_id` STRING,
  `meta_connection_id` STRING,
  `meta_account_id` STRING,
  `meta_api_version` STRING,
  `upzero_store_identifier` STRING,
  `operation_b2b` BOOL,
  `operation_b2c` BOOL,
  `history_complete` BOOL,
  `facts_complete` BOOL,
  `upzero_enabled` BOOL,
  `meta_enabled` BOOL,
  `analytics_enabled` BOOL,
  `intelligence_enabled` BOOL,
  `sync_enabled` BOOL,
  `history_from` TIMESTAMP,
  `facts_coverage_from` TIMESTAMP,
  `facts_coverage_to` TIMESTAMP,
  `purchase_order_id_effective_at` TIMESTAMP,
  `created_at` TIMESTAMP,
  `updated_at` TIMESTAMP,
  `qualifying_order_statuses` JSON,
  `history_coverage` JSON
)
CLUSTER BY status, store_id;
