CREATE TABLE IF NOT EXISTS `${project_id}.up_core.identity_links` (
  `row_key` STRING NOT NULL,
  `store_id` STRING NOT NULL,
  `source_system` STRING,
  `raw_record_id` STRING,
  `run_id` STRING,
  `observed_at` TIMESTAMP,
  `source_updated_at` TIMESTAMP,
  `payload_hash` STRING,
  `version_id` STRING,
  `transform_version` STRING,
  `link_id` STRING,
  `source_fact_id` STRING,
  `source_version_id` STRING,
  `left_namespace` STRING,
  `left_id` STRING,
  `right_namespace` STRING,
  `right_id` STRING,
  `evidence_type` STRING,
  `occurred_at` TIMESTAMP,
  `source_entity_type` STRING,
  `source_entity_id` STRING,
  `identifier_type_from` STRING,
  `identifier_value_from` STRING,
  `identifier_type_to` STRING,
  `identifier_value_to` STRING,
  `confidence_type` STRING,
  `first_seen_at` TIMESTAMP,
  `last_seen_at` TIMESTAMP
)
PARTITION BY DATE(observed_at)
CLUSTER BY store_id, source_fact_id;
