CREATE TABLE IF NOT EXISTS `${project_id}.up_core.meta_live_insights_daily_versions` (
  `row_key` STRING NOT NULL,
  `store_id` STRING NOT NULL,
  `account_id` STRING,
  `api_version` STRING,
  `contract_version` STRING,
  `observed_at` TIMESTAMP,
  `source_updated_at` TIMESTAMP,
  `level` STRING,
  `campaign_id` STRING,
  `adset_id` STRING,
  `ad_id` STRING,
  `currency` STRING,
  `timezone` STRING,
  `configuration_hash` STRING,
  `date_start` DATE,
  `date_stop` DATE,
  `impressions` INT64,
  `reach` INT64,
  `clicks` INT64,
  `link_clicks` INT64,
  `landing_page_views` NUMERIC,
  `spend` NUMERIC,
  `cpm` NUMERIC,
  `cpc` NUMERIC,
  `ctr` NUMERIC,
  `breakdown_values` JSON,
  `reporting_configuration` JSON,
  `version_id` STRING,
  `payload_hash` STRING,
  `source_system` STRING
)
PARTITION BY DATE(observed_at)
CLUSTER BY store_id, account_id;
