CREATE TABLE IF NOT EXISTS `${project_id}.up_core.meta_insights_daily` (
  `row_key` STRING NOT NULL,
  `store_id` STRING NOT NULL,
  `source_system` STRING,
  `raw_record_id` STRING,
  `run_id` STRING,
  `observed_at` TIMESTAMP,
  `source_updated_at` TIMESTAMP,
  `payload_hash` STRING,
  `version_id` STRING,
  `transform_version` STRING,
  `account_id` STRING,
  `campaign_id` STRING,
  `adset_id` STRING,
  `ad_id` STRING,
  `api_version` STRING,
  `account_currency` STRING,
  `source_timezone` STRING,
  `configuration_hash` STRING,
  `purchase_action_type` STRING,
  `date_start` DATE,
  `date_stop` DATE,
  `spend` NUMERIC,
  `frequency` NUMERIC,
  `cpm` NUMERIC,
  `cpc` NUMERIC,
  `ctr` NUMERIC,
  `landing_page_views` NUMERIC,
  `meta_reported_purchases` NUMERIC,
  `meta_reported_purchase_value` NUMERIC,
  `impressions` INT64,
  `reach` INT64,
  `clicks` INT64,
  `inline_link_clicks` INT64,
  `actions` JSON,
  `action_values` JSON,
  `breakdown_values` JSON,
  `reporting_configuration` JSON
)
PARTITION BY date_start
CLUSTER BY store_id, account_id, ad_id;
