CREATE TABLE IF NOT EXISTS `${project_id}.up_core.meta_period_insights_versions` (
  `row_key` STRING NOT NULL,
  `store_id` STRING NOT NULL,
  `account_id` STRING,
  `connection_id` STRING,
  `api_version` STRING,
  `currency` STRING,
  `timezone` STRING,
  `level` STRING,
  `campaign_id` STRING,
  `adset_id` STRING,
  `ad_id` STRING,
  `configuration_hash` STRING,
  `purchase_action_type` STRING,
  `version_id` STRING,
  `payload_hash` STRING,
  `source_system` STRING,
  `date_start` DATE,
  `date_stop` DATE,
  `impressions` INT64,
  `reach` INT64,
  `clicks` INT64,
  `link_clicks` INT64,
  `spend` NUMERIC,
  `frequency` NUMERIC,
  `ctr` NUMERIC,
  `cpc` NUMERIC,
  `cpm` NUMERIC,
  `meta_reported_purchases` NUMERIC,
  `meta_reported_purchase_value` NUMERIC,
  `reporting_configuration` JSON,
  `actions` JSON,
  `action_values` JSON,
  `observed_at` TIMESTAMP
)
PARTITION BY DATE(observed_at)
CLUSTER BY store_id, account_id, level;
