CREATE TABLE IF NOT EXISTS `${project_id}.up_core.orders` (
  `row_key` STRING NOT NULL,
  `store_id` STRING NOT NULL,
  `source_system` STRING,
  `raw_record_id` STRING,
  `run_id` STRING,
  `observed_at` TIMESTAMP,
  `source_updated_at` TIMESTAMP,
  `payload_hash` STRING,
  `version_id` STRING,
  `transform_version` STRING,
  `order_id` STRING,
  `customer_id` STRING,
  `order_status` STRING,
  `payment_status` STRING,
  `payment_method` STRING,
  `payment_method_name` STRING,
  `installments` INT64,
  `customer_snapshot` JSON,
  `shipping_address` JSON,
  `created_at` TIMESTAMP,
  `updated_at` TIMESTAMP,
  `subtotal` NUMERIC,
  `discount` NUMERIC,
  `shipping` NUMERIC,
  `total` NUMERIC,
  `requested_total` NUMERIC,
  `fulfilled_total` NUMERIC,
  `total_items_qty` INT64,
  `requested_items_qty` INT64,
  `fulfilled_items_qty` INT64,
  `items_count` INT64,
  `item_ids` JSON
)
PARTITION BY DATE(created_at)
CLUSTER BY store_id, order_id;
