CREATE TABLE IF NOT EXISTS `${project_id}.up_core.touchpoints` (
  `row_key` STRING NOT NULL,
  `store_id` STRING NOT NULL,
  `source_system` STRING,
  `raw_record_id` STRING,
  `run_id` STRING,
  `observed_at` TIMESTAMP,
  `source_updated_at` TIMESTAMP,
  `payload_hash` STRING,
  `version_id` STRING,
  `transform_version` STRING,
  `fact_id` STRING,
  `event_id` STRING,
  `event_name` STRING,
  `user_id` STRING,
  `anonymous_id` STRING,
  `session_id` STRING,
  `visitor_id` STRING,
  `fbclid` STRING,
  `fbc` STRING,
  `fbp` STRING,
  `gclid` STRING,
  `utm_source` STRING,
  `utm_medium` STRING,
  `utm_campaign` STRING,
  `utm_content` STRING,
  `utm_term` STRING,
  `source` STRING,
  `channel` STRING,
  `device_type` STRING,
  `landing_url` STRING,
  `referrer` STRING,
  `landing_host` STRING,
  `landing_path` STRING,
  `referrer_host` STRING,
  `product_id` STRING,
  `product_variant_id` STRING,
  `category_id` STRING,
  `order_id` STRING,
  `meta_campaign_id` STRING,
  `meta_adset_id` STRING,
  `meta_ad_id` STRING,
  `meta_adset_name` STRING,
  `parser_version` STRING,
  `parse_status` STRING,
  `occurred_at` TIMESTAMP,
  `quantity` INT64,
  `value` NUMERIC,
  `touchpoint_id` STRING,
  `source_fact_id` STRING
)
PARTITION BY DATE(occurred_at)
CLUSTER BY store_id, session_id;
