/** Synthetic records only. Never imported by UI components. */
import type {
  Campaign,
  Customer,
  Geography,
  Integration,
  Order,
  Product,
  Retention,
  TimelineEvent,
} from "@/types/domain";
export const customers: Customer[] = [
  {
    id: "c1",
    name: "Ateliê Jardim",
    city: "São Paulo",
    state: "SP",
    orders: 8,
    requested: "48320",
    fulfilled: "42860",
    lastPurchase: "2026-09-27",
    firstPurchase: "2026-03-12",
    segment: "Recorrente",
    paid: true,
  },
  {
    id: "c2",
    name: "Casa de Linho",
    city: "Belo Horizonte",
    state: "MG",
    orders: 5,
    requested: "32800",
    fulfilled: "30240",
    lastPurchase: "2026-09-25",
    firstPurchase: "2026-05-03",
    segment: "Recorrente",
    paid: true,
  },
  {
    id: "c3",
    name: "Essência Boutique",
    city: "Curitiba",
    state: "PR",
    orders: 1,
    requested: "12680",
    fulfilled: "11840",
    lastPurchase: "2026-09-26",
    firstPurchase: "2026-09-26",
    segment: "Primeira observada",
    paid: false,
  },
  {
    id: "c4",
    name: "Vila Serena",
    city: "Rio de Janeiro",
    state: "RJ",
    orders: 4,
    requested: "28940",
    fulfilled: "25100",
    lastPurchase: "2026-09-24",
    firstPurchase: "2026-04-10",
    segment: "Recorrente",
    paid: true,
  },
  {
    id: "c5",
    name: "Studio Pétala",
    city: "Florianópolis",
    state: "SC",
    orders: 3,
    requested: "21300",
    fulfilled: "18580",
    lastPurchase: "2026-09-23",
    firstPurchase: "2026-06-15",
    segment: "Recorrente",
    paid: false,
  },
  {
    id: "c6",
    name: "Flor de Algodão",
    city: "Goiânia",
    state: "GO",
    orders: 2,
    requested: "18760",
    fulfilled: "16290",
    lastPurchase: "2026-09-22",
    firstPurchase: "2026-08-02",
    segment: "Recorrente",
    paid: true,
  },
  {
    id: "c7",
    name: "Maré Boutique",
    city: "Salvador",
    state: "BA",
    orders: 1,
    requested: "8620",
    fulfilled: "8400",
    lastPurchase: "2026-09-21",
    firstPurchase: "2026-09-21",
    segment: "Primeira observada",
    paid: true,
  },
  {
    id: "c8",
    name: "Bem Vestir",
    city: "Porto Alegre",
    state: "RS",
    orders: 6,
    requested: "34800",
    fulfilled: "30450",
    lastPurchase: "2026-09-20",
    firstPurchase: "2026-02-15",
    segment: "Recorrente",
    paid: false,
  },
];
export const orders: Order[] = customers.flatMap((c, index) =>
  Array.from({ length: c.orders }, (_, n) => ({
    id: `${2100 + index * 10 + n}`,
    customer_id: c.id,
    date: `2026-09-${String(27 - n * 2).padStart(2, "0")}`,
    requested: (Number(c.requested) / c.orders).toFixed(2),
    fulfilled: (Number(c.fulfilled) / c.orders).toFixed(2),
    requestedQuantity: 48,
    fulfilledQuantity: n % 3 === 0 ? 40 : 48,
    status: n === 0 ? "CONFIRMED" : n === 1 ? "SHIPPED" : "INVOICED",
    paid: c.paid,
  })),
);
export const products: Product[] = [
  {
    id: "p1",
    category: "Vestidos",
    active: true,
    salePrice: "72.00",
    colorHex: "#C9B494",
    name: "Vestido midi linho",
    sku: "VT-2231",
    requested: "132480",
    fulfilled: "112600",
    units: 1840,
    customers: 92,
    orders: 114,
    share: 28,
    sizes: { P: true, M: true, G: false, GG: false },
    abc: "A",
    views: 8600,
    cart: 1200,
    checkout: 730,
    stock: 184,
    sellThrough: 78,
    turnover: 3.2,
    coverage: 18,
    color: "Areia",
  },
  {
    id: "p2",
    category: "Conjuntos",
    active: true,
    salePrice: "94.00",
    colorHex: "#1A1A1A",
    name: "Conjunto alfaiataria",
    sku: "CJ-1180",
    requested: "118910",
    fulfilled: "109800",
    units: 1265,
    customers: 78,
    orders: 96,
    share: 25,
    sizes: { P: true, M: true, G: true, GG: true },
    abc: "A",
    views: 6400,
    cart: 870,
    checkout: 520,
    stock: 420,
    sellThrough: 65,
    turnover: 2.8,
    coverage: 32,
    color: "Preto",
  },
  {
    id: "p3",
    category: "Calças",
    active: true,
    salePrice: "64.00",
    colorHex: "#F4EFE5",
    name: "Calça pantalona crepe",
    sku: "CL-0942",
    requested: "96640",
    fulfilled: "88200",
    units: 1510,
    customers: 65,
    orders: 88,
    share: 20,
    sizes: { P: true, M: true, G: true, GG: true },
    abc: "A",
    views: 5800,
    cart: 720,
    checkout: 470,
    stock: 312,
    sellThrough: 72,
    turnover: 3.1,
    coverage: 24,
    color: "Off-white",
  },
  {
    id: "p4",
    category: "Blusas",
    active: true,
    salePrice: "36.00",
    colorHex: "#C96B4B",
    name: "Blusa ciganinha viscose",
    sku: "BL-3307",
    requested: "71360",
    fulfilled: "64400",
    units: 2230,
    customers: 53,
    orders: 74,
    share: 15,
    sizes: { P: true, M: true, G: true, GG: false },
    abc: "B",
    views: 4700,
    cart: 680,
    checkout: 390,
    stock: 168,
    sellThrough: 82,
    turnover: 4.2,
    coverage: 12,
    color: "Terracota",
  },
  {
    id: "p5",
    category: "Macacões",
    active: false,
    salePrice: "90.00",
    colorHex: "#767B4E",
    name: "Macacão longo",
    sku: "MC-0716",
    requested: "57600",
    fulfilled: "52900",
    units: 640,
    customers: 38,
    orders: 56,
    share: 12,
    sizes: { P: true, M: true, G: true, GG: true },
    abc: "C",
    views: 3300,
    cart: 410,
    checkout: 260,
    stock: 280,
    sellThrough: 48,
    turnover: 1.9,
    coverage: 41,
    color: "Oliva",
  },
];
export const campaigns: Campaign[] = [
  {
    id: "cmp1",
    name: "Primavera · Novas conexões",
    spend: "18240",
    customers: 58,
    newCustomers: null,
    orders: 72,
    requested: "284600",
    fulfilled: "249400",
    roasRequested: "15.60",
    roasFulfilled: "13.67",
    cac: null,
  },
  {
    id: "cmp2",
    name: "Essenciais · Recompra",
    spend: "12480",
    customers: 42,
    newCustomers: null,
    orders: 64,
    requested: "198300",
    fulfilled: "176600",
    roasRequested: "15.89",
    roasFulfilled: "14.15",
    cac: null,
  },
  {
    id: "cmp3",
    name: "Alto Verão · Descoberta",
    spend: "8640",
    customers: 23,
    newCustomers: null,
    orders: 28,
    requested: "104800",
    fulfilled: "89600",
    roasRequested: "12.13",
    roasFulfilled: "10.37",
    cac: null,
  },
];
export const integrations: Integration[] = [
  {
    id: "i1",
    name: "UP Zero",
    type: "ERP",
    endpoint: "",
    status: "CONNECTED",
    lastRun: "2026-09-28T12:40:00Z",
    lastError: null,
    updated: "2026-09-28T12:40:00Z",
  },
  {
    id: "i2",
    name: "Meta Ads",
    type: "Meta Ads",
    endpoint: "",
    account_id: "demo-account",
    status: "PENDING",
    lastRun: null,
    lastError: null,
    updated: "2026-09-28T12:00:00Z",
  },
  {
    id: "i3",
    name: "Google Ads",
    type: "Google Ads",
    endpoint: "",
    status: "PENDING",
    lastRun: null,
    lastError: null,
    updated: "2026-09-28T12:00:00Z",
  },
  {
    id: "i4",
    name: "TikTok Ads",
    type: "TikTok Ads",
    endpoint: "",
    status: "PENDING",
    lastRun: null,
    lastError: null,
    updated: "2026-09-28T12:00:00Z",
  },
  {
    id: "i5",
    name: "Analytics",
    type: "Analytics",
    endpoint: "",
    status: "ERROR",
    lastRun: "2026-09-27T08:00:00Z",
    lastError: "Janela demonstrativa incompleta",
    updated: "2026-09-27T08:00:00Z",
  },
];
export const timeline: Omit<TimelineEvent, "customer_id" | "store_id">[] = [
  {
    id: "t1",
    type: "paid_touch",
    date: "2026-09-20T10:20:00Z",
    title: "Primeiro contato com a campanha",
    detail: "Primavera · Novas conexões",
    evidence: "CUSTOMER_JOURNEY",
  },
  {
    id: "t2",
    type: "register_submitted",
    date: "2026-09-20T10:24:00Z",
    title: "Cadastro enviado",
    detail: "Solicitação de acesso ao atacado",
    evidence: "DIRECT",
  },
  {
    id: "t3",
    type: "register_approved",
    date: "2026-09-21T14:00:00Z",
    title: "Cadastro aprovado",
    detail: "Acesso comercial liberado",
    evidence: "DIRECT",
  },
  {
    id: "t4",
    type: "product_view",
    date: "2026-09-22T11:32:00Z",
    title: "Produto visualizado",
    detail: "Vestido midi linho",
    evidence: "CUSTOMER_JOURNEY",
  },
  {
    id: "t5",
    type: "order_created",
    date: "2026-09-23T15:10:00Z",
    title: "Pedido recebido",
    detail: "Solicitado e atendido preservados separadamente",
    evidence: "DIRECT",
  },
  {
    id: "t6",
    type: "repeat_purchase",
    date: "2026-09-27T13:50:00Z",
    title: "Nova compra observada",
    detail: "Participação de mídia não é atribuição exclusiva",
    evidence: "DIRECT",
  },
];
export const geography: Omit<
  Geography,
  "fulfilled" | "influencedCustomers" | "averageTicket" | "cities"
>[] = customers.map((c, i) => ({
  uf: c.state,
  name: (
    {
      SP: "São Paulo",
      MG: "Minas Gerais",
      PR: "Paraná",
      RJ: "Rio de Janeiro",
      SC: "Santa Catarina",
      GO: "Goiás",
      BA: "Bahia",
      RS: "Rio Grande do Sul",
    } as Record<string, string>
  )[c.state],
  requested: Number(c.requested) * 3,
  customers: 95 - i * 8,
  orders: 180 - i * 13,
  newCustomers: null,
  approvedWithoutPurchase: null,
  conversionRate: null,
}));
export const retention: Retention[] = Array.from({ length: 5 }, (_, i) => ({
  sequence: i === 4 ? "Compra 5+" : `Compra ${i + 1}`,
  customers: [412, 278, 194, 128, 86][i],
  mean: i ? 27 + i * 3 : null,
  median: i ? 23 + i * 3 : null,
  rate: [100, 67.5, 47.1, 31.1, 20.9][i],
  cohorts: [30, 60, 90, 180, 365].map((day, j) => ({
    day,
    rate: j > 2 ? null : Math.max(12, 74 - i * 11 + j * 3),
  })),
}));

// Explicit synthetic approval dates. These are not inferred from order statuses.
export const approvals: Record<string, string> = {
  c1: "2026-09-13",
  c2: "2026-09-17",
  c3: "2026-09-22",
  c4: "2026-09-10",
  c5: "2026-08-30",
  c6: "2026-08-10",
  c7: "2026-07-10",
  c8: "2026-09-17",
};
